---
applications:
  - name: api
    instances: 1
    memory: 1G
    disk_quota: 1G
    stack: cflinuxfs3
    buildpacks:
      - python_buildpack
    path: ../
    routes:
      - route: fec-stage-api.app.cloud.gov
    services:
      - fec-api-elasticsearch
      - fec-elasticache-redis
      - fec-creds-stage
      - fec-s3-api
      - fec-s3-snapshot
    env:
      FEC_API_USE_PROXY: true
      FEC_API_RESTRICT_DOWNLOADS: true
      APP_NAME: fec | api | stage
