---
applications:
  - name: api
    instances: 10
    memory: 2.5G
    disk_quota: 1G
    stack: cflinuxfs3
    buildpacks:
      - python_buildpack
    path: ../
    routes:
      - route: fec-prod-api.app.cloud.gov
    services:
      - fec-api-elasticsearch
      - fec-elasticache-redis
      - fec-creds-prod
      - fec-s3-api
      - fec-s3-snapshot
    env:
      FEC_API_USE_PROXY: true
      FEC_API_RESTRICT_DOWNLOADS: true
      APP_NAME: fec | api | prod
      PRODUCTION: True
